version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: vasilevvladv22/apiyamdb:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    depends_on:
      - web
volumes:
  postgres_data:
  static_value:
  media_value:

